# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

   

    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
    
    - name: Create PR
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
        gh repo fork --clone --remote https://github.com/baikinkirill/Landing-Front.git --remote-name forkedRep
        copy ./package.json ./forkedRep/package.json
        cd forkedRep
        git add .
        git commit -m "update package.json"
        git push
        gh pr create --title "Update package.json" --base master --head master -a baikinkirill -R github.com/baikinkirill/Landing-Front --body ""
